spring:
  application:
    name: house-business
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9999

mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml
  type-aliases-package: com.nil.house.business.model;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
